Fix broken stdout->stderr redirects

diff --git a/et b/et
--- a/et
+++ b/et
@@ -35,7 +35,7 @@ for f in "$@"; do
 	expand -t$tabw <"$f" >"$tmpf"
 	if [ $? -ne 0 ]; then
 		ev=$?
-		echo "$0: error expanding $f into $tmpf, stopping" 2>&1
+		echo "$0: error expanding $f into $tmpf, stopping" 1>&2
 		exit $ev
 	fi
 
@@ -47,7 +47,7 @@ for f in "$@"; do
 		cat "$tmpf" >"$f"
 		if [ $? -ne 0 ]; then
 			ev=$?
-			echo "$0: error writing $tmpf into $f, stopping" 2>&1
+			echo "$0: error writing $tmpf into $f, stopping" 1>&2
 			exit $ev
 		fi
 	fi
diff --git a/fmtbl b/fmtbl
--- a/fmtbl
+++ b/fmtbl
@@ -65,7 +65,7 @@ if [ $bopt -eq 0 ]; then
 	cat >"$file"
 	if [ $? -ne 0 ]; then
 		ev=$?
-		echo "$0: error writing stdin into $file, stopping" 2>&1
+		echo "$0: error writing stdin into $file, stopping" 1>&2
 		exit $ev
 	fi
 
@@ -74,7 +74,7 @@ if [ $bopt -eq 0 ]; then
 	bullet="$(sed 1q "$file" | awk '{ print $1 }')"
 	if [ $? -ne 0 ]; then
 		ev=$?
-		echo "$0: error reading first line of $file, stopping" 2>&1
+		echo "$0: error reading first line of $file, stopping" 1>&2
 		exit $ev
 	fi
 fi
diff --git a/fmtp b/fmtp
--- a/fmtp
+++ b/fmtp
@@ -39,7 +39,7 @@ trap 'rm -f -- "$tmpf"' EXIT
 cat >"$tmpf"
 if [ $? -ne 0 ]; then
 	ev=$?
-	echo "$0: error writing stdin into $tmpf, stopping" 2>&1
+	echo "$0: error writing stdin into $tmpf, stopping" 1>&2
 	exit $ev
 fi
 
@@ -49,7 +49,7 @@ if [ "$prefix" = "" ]; then
 	prefix="$(sed 1q "$tmpf" | awk '{ print $1 }')"
 	if [ $? -ne 0 ]; then
 		ev=$?
-		echo "$0: error reading first line of $tmpf, stopping" 2>&1
+		echo "$0: error reading first line of $tmpf, stopping" 1>&2
 		exit $ev
 	fi
 
@@ -77,7 +77,7 @@ if [ $? -eq 0 ]; then
 	ichar="$(sed 1q "$tmpf" | $sed 's/\(.\).*/\1/')"
 	if [ $? -ne 0 ]; then
 		ev=$?
-		echo "$0: error reading first character of $tmpf, stopping" 2>&1
+		echo "$0: error reading first character of $tmpf, stopping" 1>&2
 		exit $ev
 	fi
 	postexpand=cat
diff --git a/fmts b/fmts
--- a/fmts
+++ b/fmts
@@ -14,7 +14,7 @@ trap 'rm -f -- "$tmpf"' EXIT
 cat >"$tmpf"
 if [ $? -ne 0 ]; then
 	ev=$?
-	echo "$0: error writing stdin into $tmpf, stopping" 2>&1
+	echo "$0: error writing stdin into $tmpf, stopping" 1>&2
 	exit $ev
 fi
 
@@ -22,7 +22,7 @@ fi
 token="$(sed 1q "$tmpf" | awk '{ print $1 }')"
 if [ $? -ne 0 ]; then
 	ev=$?
-	echo "$0: error reading first line of $tmpf, stopping" 2>&1
+	echo "$0: error reading first line of $tmpf, stopping" 1>&2
 	exit $ev
 fi
 
diff --git a/fmtw b/fmtw
--- a/fmtw
+++ b/fmtw
@@ -42,7 +42,7 @@ if [ $? -eq 0 ]; then
 	ichar="$(sed 1q "$tmpf" | $sed 's/\(.\).*/\1/')"
 	if [ $? -ne 0 ]; then
 		ev=$?
-		echo "$0: error reading first character of $tmpf, stopping" 2>&1
+		echo "$0: error reading first character of $tmpf, stopping" 1>&2
 		exit $ev
 	fi
 	postexpand=cat
diff --git a/mkexe b/mkexe
--- a/mkexe
+++ b/mkexe
@@ -3,19 +3,19 @@
 set -u
 
 if [ $# -eq 0 ]; then
-	echo "usage: $0 [files ...]" 2>&1
-	echo "touch and chmod +x all paths provided as arguments" 2>&1
+	echo "usage: $0 [files ...]" 1>&2
+	echo "touch and chmod +x all paths provided as arguments" 1>&2
 	exit 1
 fi
 
 for f in "$@"; do
 	touch -- "$f"
 	if [ $? -ne 0 ]; then
-		echo "$0: failed to touch $f, continuing" 2>&1
+		echo "$0: failed to touch $f, continuing" 1>&2
 	else
 		chmod +x "$f"
 		if [ $? -ne 0 ]; then
-			echo "$0: failed to chmod +x $f, continuing" 2>&1
+			echo "$0: failed to chmod +x $f, continuing" 1>&2
 		fi
 	fi
 done
diff --git a/ut b/ut
--- a/ut
+++ b/ut
@@ -45,7 +45,7 @@ for f in "$@"; do
 	unexpand $targ <"$f" >"$tmpf"
 	if [ $? -ne 0 ]; then
 		ev=$?
-		echo "$0: error unexpanding $f into $tmpf, stopping" 2>&1
+		echo "$0: error unexpanding $f into $tmpf, stopping" 1>&2
 		exit $ev
 	fi
 
@@ -57,7 +57,7 @@ for f in "$@"; do
 		cat "$tmpf" >"$f"
 		if [ $? -ne 0 ]; then
 			ev=$?
-			echo "$0: error writing $tmpf into $f, stopping" 2>&1
+			echo "$0: error writing $tmpf into $f, stopping" 1>&2
 			exit $ev
 		fi
 	fi
