Improve error handling
Ignoring pipes for now, which will be dealt with separately.

diff --git a/et b/et
--- a/et
+++ b/et
@@ -20,16 +20,23 @@ done
 shift $(($OPTIND - 1))
 
 if [ $# -eq 0 ]; then
-	expand -t$tabw
-	exit $?
+	exec expand -t$tabw
 fi
 
 # create a temporary file which is deleted on exit
 tmpf=$(mktemp)
+if [ $? -ne 0 ]; then
+	exit $?
+fi
 trap 'rm -f -- "$tmpf"' EXIT
 
 for f in "$@"; do
 	expand -t$tabw <"$f" >"$tmpf"
+	if [ $? -ne 0 ]; then
+		ev=$?
+		echo "$0: error expanding $f into $tmpf, stopping" 2>&1
+		exit $ev
+	fi
 
 	# skip rewriting the file if nothing changed
 	if ! cmp "$tmpf" "$f" 2>&1 >/dev/null; then
@@ -37,5 +44,10 @@ for f in "$@"; do
 		# file so that the original metadata (e.g., permissions) are
 		# preserved
 		cat "$tmpf" >"$f"
+		if [ $? -ne 0 ]; then
+			ev=$?
+			echo "$0: error writing $tmpf into $f, stopping" 2>&1
+			exit $ev
+		fi
 	fi
 done
diff --git a/fmtbl b/fmtbl
--- a/fmtbl
+++ b/fmtbl
@@ -54,10 +54,18 @@ file=
 if [ $bopt -eq 0 ]; then
 	# create a temporary file which is deleted on exit
 	file=$(mktemp)
+	if [ $? -ne 0 ]; then
+		exit $?
+	fi
 	trap 'rm -f -- "$file"' EXIT
 
 	# dump stdin to the temporary file
 	cat >"$file"
+	if [ $? -ne 0 ]; then
+		ev=$?
+		echo "$0: error writing stdin into $file, stopping" 2>&1
+		exit $ev
+	fi
 
 	# first non-whitespace character on first line is taken as the bullet
 	# character
diff --git a/fmtp b/fmtp
--- a/fmtp
+++ b/fmtp
@@ -9,7 +9,7 @@ usage() {
 }
 
 width=80
-while getopts hw: name; do
+while getopts w:h name; do
 	case $name in
 	w) width=$OPTARG;;
 	h) usage 1;;
@@ -25,10 +25,18 @@ fi
 
 # create a temporary file which is deleted on exit
 tmpf=$(mktemp)
+if [ $? -ne 0 ]; then
+	exit $?
+fi
 trap 'rm -f -- "$tmpf"' EXIT
 
 # dump stdin to the temporary file
 cat >"$tmpf"
+if [ $? -ne 0 ]; then
+	ev=$?
+	echo "$0: error writing stdin into $file, stopping" 2>&1
+	exit $ev
+fi
 
 # first token on first line is taken as the prefix
 prefix=`sed 1q "$tmpf" | awk '{ print $1 }'`
diff --git a/mkexe b/mkexe
--- a/mkexe
+++ b/mkexe
@@ -9,5 +9,12 @@ fi
 
 for f in "$@"; do
 	touch -- "$f"
-	chmod +x -- "$f"
+	if [ $? -ne 0 ]; then
+		echo "$0: failed to touch $f, continuing" 2>&1
+	else
+		chmod +x -- "$f"
+		if [ $? -ne 0 ]; then
+			echo "$0: failed to chmod +x $f, continuing" 2>&1
+		fi
+	fi
 done
diff --git a/ut b/ut
--- a/ut
+++ b/ut
@@ -30,16 +30,23 @@ if [ "$(uname)" = "OpenBSD" ]; then
 fi
 
 if [ $# -eq 0 ]; then
-	unexpand $targ
-	exit $?
+	exec unexpand $targ
 fi
 
 # create a temporary file which is deleted on exit
 tmpf=$(mktemp)
+if [ $? -ne 0 ]; then
+	exit $?
+fi
 trap 'rm -f -- "$tmpf"' EXIT
 
 for f in "$@"; do
 	unexpand $targ <"$f" >"$tmpf"
+	if [ $? -ne 0 ]; then
+		ev=$?
+		echo "$0: error unexpanding $f into $tmpf, stopping" 2>&1
+		exit $ev
+	fi
 
 	# skip rewriting the file if nothing changed
 	if ! cmp "$tmpf" "$f" 2>&1 >/dev/null; then
@@ -47,5 +54,10 @@ for f in "$@"; do
 		# file so that the original metadata (e.g., permissions) are
 		# preserved
 		cat "$tmpf" >"$f"
+		if [ $? -ne 0 ]; then
+			ev=$?
+			echo "$0: error writing $tmpf into $f, stopping" 2>&1
+			exit $ev
+		fi
 	fi
 done
