use set -o pipefail where it makes sense
Most shells support it, see: https://unix.stackexchange.com/a/654932

Unfortunately, the Dash shell used by Ubuntu (at least in 20.04) and
Debian doesn't yet support set -o pipefail.  I assume it eventually
will, since it's to become a POSIX standard.  For the time being, check
for Dash as a special case.

diff --git a/fmtbl b/fmtbl
--- a/fmtbl
+++ b/fmtbl
@@ -23,6 +23,11 @@
 # A space between the bullet character and subsequent text is required.
 set -u
 
+# dash doesn't (yet) support pipefail
+if [ "$(uname)" = "Linux" -a "$(readlink -f $(which sh))" != "/usr/bin/dash" ]; then
+	set -o pipefail
+fi
+
 usage() {
 	echo "usage: $0 [-w width] [-b bullet_char]" 1>&$1
 	echo "Wrap bulleted lists at given column width (default 80)." 1>&$1
@@ -71,6 +76,11 @@ if [ $bopt -eq 0 ]; then
 	# first non-whitespace character on first line is taken as the bullet
 	# character
 	bullet=$(sed 1q "$file" | awk '{ print $1 }')
+	if [ $? -ne 0 ]; then
+		ev=$?
+		echo "$0: error reading first line of $file, stopping" 2>&1
+		exit $ev
+	fi
 fi
 
 # these characters seem to work; others (like "o") may cause regex failures
diff --git a/fmtp b/fmtp
--- a/fmtp
+++ b/fmtp
@@ -3,6 +3,11 @@
 # useful for comments (e.g., "//" prefix) and quotations (">" prefix)
 set -u
 
+# dash doesn't (yet) support pipefail
+if [ "$(uname)" = "Linux" -a "$(readlink -f $(which sh))" != "/usr/bin/dash" ]; then
+	set -o pipefail
+fi
+
 usage() {
 	echo "usage: $0 [-w width]" 1>&$1
 	echo "Wrap prefixed text at given column width (default 80)." 1>&$1
@@ -41,6 +46,11 @@ fi
 
 # first token on first line is taken as the prefix
 prefix=`sed 1q "$tmpf" | awk '{ print $1 }'`
+if [ $? -ne 0 ]; then
+	ev=$?
+	echo "$0: error reading first line of $tmpf, stopping" 2>&1
+	exit $ev
+fi
 
 # Doxygen comments are "///" and batch file comments are "rem",
 # so allow prefixes <= 3 bytes; longer prefixes could be allowed
@@ -63,6 +73,11 @@ if [ $? -eq 0 ]; then
 	# back into spaces; then if (and only if) the line was indented with
 	# tabs, convert the leading indentation back into tabs.
 	ichar=`sed 1q "$tmpf" | $sed 's/\(.\).*/\1/'`
+	if [ $? -ne 0 ]; then
+		ev=$?
+		echo "$0: error reading first character of $tmpf, stopping" 2>&1
+		exit $ev
+	fi
 	postexpand=cat
 	if [ "$ichar" = "	" ]; then
 		postexpand="unexpand --first-only"
diff --git a/fmtw b/fmtw
--- a/fmtw
+++ b/fmtw
@@ -2,6 +2,11 @@
 # fmt(1) wrapper script
 set -u
 
+# dash doesn't (yet) support pipefail
+if [ "$(uname)" = "Linux" -a "$(readlink -f $(which sh))" != "/usr/bin/dash" ]; then
+	set -o pipefail
+fi
+
 usage() {
 	echo "usage: $0 [-w width]" 1>&$1
 	echo "Wrap text at given column width (default 80)." 1>&$1
@@ -39,6 +44,11 @@ if [ $? -eq 0 ]; then
 	trap 'rm -f -- "$tmpf"' EXIT
 	cat >"$tmpf"
 	ichar=`sed 1q "$tmpf" | $sed 's/\(.\).*/\1/'`
+	if [ $? -ne 0 ]; then
+		ev=$?
+		echo "$0: error reading first character of $tmpf, stopping" 2>&1
+		exit $ev
+	fi
 	postexpand=cat
 	if [ "$ichar" = "	" ]; then
 		postexpand="unexpand --first-only"
